"""
Abstract Base Provider interface for Multi-Source Evidence Collection.
"""
from abc import ABC, abstractmethod
from typing import Optional, Any
from sqlalchemy.orm import Session
from app.models.incident import Incident


class EvidencePayload:
    """Standardized internal representation of evidence generated by a provider."""
    def __init__(
        self,
        source_code: str,
        provider_name: str,
        confidence: float,
        evidence_type: str,
        agrees_with_spill: bool = True,
        quality_score: float = 1.0,
        data_origin: str = "SIMULATED",
        evidence_metadata: Optional[dict[str, Any]] = None,
        notes: Optional[str] = None,
    ):
        self.source_code = source_code
        self.provider_name = provider_name
        self.confidence = max(0.0, min(1.0, float(confidence)))
        self.evidence_type = evidence_type
        self.agrees_with_spill = agrees_with_spill
        self.quality_score = max(0.0, min(1.0, float(quality_score)))
        self.data_origin = data_origin  # LIVE, HISTORICAL, SIMULATED
        self.evidence_metadata = evidence_metadata or {}
        self.notes = notes


class BaseEvidenceProvider(ABC):
    """
    Abstract base class for all evidence providers (Satellite, Drone, Citizen, AIS, Metocean).
    Each provider collects or evaluates evidence for a specific incident.
    """
    
    @property
    @abstractmethod
    def source_code(self) -> str:
        """Unique identifier code for the source category (e.g. SATELLITE, DRONE)."""
        pass

    @property
    @abstractmethod
    def default_weight(self) -> float:
        """Default score weight (e.g., 0.30 for Satellite, 0.20 for Drone)."""
        pass

    @abstractmethod
    def collect_evidence(self, incident: Incident, db: Session) -> EvidencePayload:
        """
        Gathers or evaluates evidence for the given incident.
        Returns an EvidencePayload instance.
        """
        pass
